spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://localhost:5432/sns
  username: ekgus
  password: 1111
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: test_simple.sns-application-2024-07.secret_key
  # 30 days
  token.expired-time-ms: 2592000000